apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-template.fullname" . }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  PGUSER: {{ default "" .Values.DB.PGUSER | b64enc | quote }}
  PGDB: {{ default "" .Values.DB.PGDB | b64enc | quote }}
  PGHOST: {{ default "" .Values.DB.PGHOST | b64enc | quote }}
  PGPORT: {{ default "" .Values.DB.PGPORT | b64enc | quote }}
  PGPASS: {{ default "" .Values.DB.PGPASS | b64enc | quote }}
